{
  "openapi": "3.0.0",
  "info": {
    "title": "tpgcCLI",
    "version": "1.0",
    "contact": {
      "name": "CRISTIAN PEÑALOZA",
      "email": "cpenaloza@pentafinanciero.cl",
      "url": "www.pentafinanciero.cl"
    },
    "description": "CRUD tabla de entidades (TPGC_CLI) de base de datos ODS (BPGC:GES_CMR)"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/tpgcCLI/create": {
      "post": {
        "summary": "Crear Entidad",
        "operationId": "post-tpgcCLI-create",
        "responses": {
          "200": {
            "description": "Creacion de cliente exitoso"
          }
        },
        "description": "Crea cliente en base de datos",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "Content-Type",
            "description": "Le indica al cliente cuál es realmente el tipo de contenido del contenido devuelto. Ej: application/json",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "tipodoc": {
                    "type": "string",
                    "description": "Tipo de documento Ej:pasaporte, Rut"
                  },
                  "rut": {
                    "type": "string",
                    "description": "Rut de Cliente persona o empresa"
                  },
                  "Identificacion": {
                    "type": "string",
                    "description": "Razon Social del Cliente"
                  },
                  "personaEmpresa": {
                    "type": "string",
                    "description": "Si cliente es Persona o Empresa"
                  },
                  "paisCodigo": {
                    "type": "string",
                    "description": "Codigo del Pais de Origen del Cliente"
                  },
                  "idCliCore": {
                    "type": "string",
                    "description": "ID ENTIDAD CLIENTE entregado por el servicio de Core Cliente"
                  }
                },
                "required": [
                  "tipodoc",
                  "rut",
                  "Identificacion",
                  "personaEmpresa",
                  "paisCodigo",
                  "idCliCore"
                ]
              },
              "examples": {
                "Ejemplo": {
                  "value": {
                    "tipodoc": "1",
                    "rut": "995014807",
                    "identificacion": "PENTA FINANCIERO S.A",
                    "personaEmpresa": "EMPRESA",
                    "paisCodigo": 997,
                    "idCliCore": "123"
                  }
                }
              }
            }
          },
          "description": "Estructura de datos requerida para la creacion del registro"
        }
      }
    },
    "/tpgcCLI/Select/{rut}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "rut",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Consulta por RUT",
        "tags": [],
        "responses": {
          "200": {
            "description": "Ok Cliente Encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "cli_id": {
                      "type": "number",
                      "description": "Codigo Cliente segun Core de Cliente"
                    },
                    "cli_etd_tip": {
                      "type": "string",
                      "description": "tipo de entidad (EMPRESA / PERSONA)"
                    },
                    "cli_rzn_scl": {
                      "type": "string",
                      "description": "Razon Social o Nombre deñ Cliente"
                    },
                    "cli_pai": {
                      "type": "string",
                      "description": "Codigo Pais "
                    },
                    "cli_tip_doc": {
                      "type": "string",
                      "description": "Tipo de Documento"
                    },
                    "cli_num_doc": {
                      "type": "string",
                      "description": "Numero del documento (RUT)"
                    }
                  },
                  "required": [
                    "cli_id",
                    "cli_etd_tip",
                    "cli_rzn_scl",
                    "cli_pai",
                    "cli_tip_doc",
                    "cli_num_doc"
                  ]
                },
                "examples": {
                  "Ejemplo": {
                    "value": {
                      "cli_id": 123,
                      "cli_etd_tip": "PERSONA",
                      "cli_rzn_scl": "JUANITO PEREZ",
                      "cli_pai": 997,
                      "cli_tip_doc": "RUT",
                      "cli_num_doc": "19"
                    }
                  }
                }
              }
            }
          },
          "204": {
            "description": "Cliente NO encontrado"
          }
        },
        "operationId": "get-tpgcCLI-Select-rut",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "rut": {
                    "type": "string",
                    "description": "Rut a Buscar"
                  }
                },
                "required": [
                  "rut"
                ]
              },
              "examples": {
                "Ejemplo": {
                  "value": {
                    "rut": "122436756"
                  }
                }
              }
            },
            "application/xml": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          },
          "description": "Estructura de datos requerida para la consulta del registro"
        },
        "parameters": [],
        "description": "Selecciona un cliente segun campo rut"
      }
    },
    "/tpgcCLI/update/cuenta/{rut}": {
      "post": {
        "summary": "Actualiza Cuenta",
        "tags": [],
        "responses": {
          "200": {
            "description": "Actualizacion de cuenta exitoso"
          }
        },
        "operationId": "post-tpgcCLI-update-cuenta",
        "description": "Actualiza la informacion de la cuenta recibida desde el canal en forma transitoria",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "description": "Le indica al cliente cuál es realmente el tipo de contenido del contenido devuelto. Ej: application/json",
            "required": true,
            "name": "Content-Type"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "examples": {
                "Ejemplo": {
                  "value": {
                    "idCliCore": 123,
                    "origen": "OCTA",
                    "tipo": "CUENTA",
                    "rutcli": "766967418",
                    "banco": "CHILE",
                    "rutcta": "122436756",
                    "tipcta": "CORRIENTE",
                    "numcta": "00000765",
                    "email": "jperez@gmail.com"
                  }
                }
              }
            }
          },
          "description": "Estructura Requerida"
        }
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "rut",
          "in": "path",
          "required": true
        }
      ]
    },
    "/tpgcCLI/update/contacto/{rut}": {
      "post": {
        "summary": "Actualiza Contacto",
        "tags": [],
        "responses": {
          "200": {
            "description": "Actualizacion de contacto exitoso"
          },
          "": {
            "description": "Estructura Requerida"
          }
        },
        "operationId": "post-tpgcCLI-update-contacto",
        "description": "Actualiza la informacion del contacto recibida desde el canal en forma transitoria",
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "description": "Le indica al cliente cuál es realmente el tipo de contenido del contenido devuelto. Ej: application/json",
            "name": "Content-Type",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "examples": {
                "Ejemplo": {
                  "value": {
                    "idCliCore": 123,
                    "origen": "OCTA",
                    "tipo": "CONTACTO",
                    "rutcli": "122436756",
                    "telefono": "936722161",
                    "direccion": "Av. El Bosque Norte 0440, piso 12, Las Condes / Santiago / Chile",
                    "Email": "javier.guajardo@gmail.com",
                    "contactos": [
                      {
                        "nombre": "Juan Perez",
                        "Cargo": "Jefe de Finanzas",
                        "fono": "98788999",
                        "email": "jperez@gmail.com",
                        "Area": "Finanzas"
                      }
                    ]
                  }
                }
              }
            }
          },
          "description": "Estructura Requerida"
        }
      },
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "rut",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "components": {
    "securitySchemes": {
      "API Key": {
        "name": "API Key",
        "type": "apiKey",
        "in": "header",
        "description": "Clave para identificacion y autorizacion para uso del servicios"
      }
    }
  }
}